### ISSUE TITLE
Spring "Less is More"

### ISSUE THREAD

**Issue by almeidaah** [javabahia/JVM-Links#12]
Link : https://www.linkedin.com/pulse/spring-less-more-fernando-almeida
Se você é desenvolvedor ou trabalha com tecnologias de desenvolvimento web, já deve ter ouvido falar um pouco(ou muito) do Spring Framework para desenvolvimento de aplicações Java Enterprise(JEE)...

**Comment by antoniolazaro** [comment]
@almeidaah tudo bem? Seu link será publicado na edição dessa semana... Muito obrigado pela participação! No JVM #5
