### ISSUE TITLE
COMPUTAÇÃO APLICADA ? O QUE É ISSO ?

### ISSUE THREAD

**Issue by fgtorres-zz** [javabahia/JVM-Links#14]
Link : http://www.fgtorres.com.br/2017/02/15/computacao-aplicada-o-que-e-isso/
Desde a graduação eu sempre fui inquieto com o que iria fazer após pegar o diploma de Sistemas de Informação. Parece algo simples, mas não é ! A área de computação tem diversas áreas e escolher qual a sua carreira para o futuro é algo construído aos poucos.

**Comment by antoniolazaro** [comment]
@fgtorres tudo bem? Seu link será publicado na edição dessa semana... Muito obrigado pela participação! No JVM #05
