### ISSUE TITLE
No More DAOs

### ISSUE THREAD

**Issue by rponte** [javabahia/JVM-Links#16]
**Link**: http://www.rponte.com.br/2009/06/08/no-more-daos/
**Breve descrição**: É muito fácil seguir receitas de bolo ou decisões arquiteturais sem se questionar se elas funcionam pro seu projeto. Uma das que mais incomodam é o uso do padrão de projetos **DAO**. Embora este padrão fosse uma solução quase que mandatório há 10 anos atrás, hoje em dia com a evolução dos frameworks ORM ele perdeu força, afinal de contas, tecnologias como JPA e Hibernate já nos fornecem uma API que funciona como nosso DAO genérico. Por esse motivo e alguns outros, as chances são que sua arquitetura não precise de uma camada DAO.

**Comment by antoniolazaro** [comment]
alô @rponte esse link será publicado na edição de hoje do JVM Links. Obrigado pela colaboração.
