### ISSUE TITLE
[Vídeo de Palestra] Migrations for Java: Evoluindo seu banco de dados de maneira incremental

### ISSUE THREAD

**Issue by rponte** [javabahia/JVM-Links#17]
**Link:** https://www.youtube.com/watch?v=BQICWePrLg0
**Slides**:  https://www.slideshare.net/rponte/migrations-for-java-jvacejavou4
**Descrição**: Assim como as Migrations no mundo Ruby On Rails, o mundo Java também possui alternativas para evoluir o banco de dados de uma aplicação. Aprenda como você e sua equipe podem evoluir de maneira iterativa e incremental seu banco de dados – já em produção – durante a criação da sua aplicação. 

Serão apresentados os problemas e desafios mais comuns de não utilizar uma ferramenta de migrations para gerenciar a evolução do banco de dados, e os benefícios que esta ferramenta traz em ambiente de desenvolvimento e produção. 

Também serão apresentados opções de migrations para Java, suas principais diferenças e a experiência do palestrante ao adotar uma dessas ferramentas em projetos com bancos de dados criados do zero, e também projetos que precisam manter o legado.

**Comment by antoniolazaro** [comment]
@rponte como sempre compartilhando conteúdo de extrema qualidade. Esse é um tema bem crítico e não vejo muitas equipes usando. Acho que muitos times dev focam no projeto/código e não tentam melhorar seus processos.

**Comment by antoniolazaro** [comment]
@rponte link será publicado na edição de hoje do JVM Links.
