### ISSUE TITLE
VOCÊ SABE COMPARAR DUAS SEQUÊNCIAS DE DNA, USANDO ALGORITMO?

### ISSUE THREAD

**Issue by fgtorres-zz** [javabahia/JVM-Links#21]
http://www.fgtorres.com.br/2017/02/26/voce-sabe-comparar-duas-sequencias-de-dna-usando-algoritmo/

**Comment by antoniolazaro** [comment]
Alô @fgtorres. Obrigado pela colaboração. O post está sendo feito e será publicado essa semana.
