### ISSUE TITLE
Aplicação prática do Padrão Proxy

### ISSUE THREAD

**Issue by luksrn** [javabahia/JVM-Links#25]
Titulo: Aplicação prática do Padrão Proxy
Tags: Padrões de projeto, Proxy
Link: https://luksrn.wordpress.com/2017/03/02/aplicacao-pratica-do-padrao-proxy/
Breve descrição: Neste artigo é apresentado a aplicabilidade do padrão proxy no cenário dos pool de conexões, onde é descrito o ciclo de vida de uma conexão neste pool e como o padrão proxy resolve um requisito essencial.

**Comment by antoniolazaro** [comment]
Obrigado pela contribuição @luksrn !!
