### ISSUE TITLE
Escolha o seu projeto Open Source na área de saúde !

### ISSUE THREAD

**Issue by fgtorres-zz** [javabahia/JVM-Links#27]
Título: Escolha o seu projeto Open Source na área de saúde !
Resumo: Você sabe o que é um software open source ? Como eles são criados e mantidos ? Será que existem projetos desse tipo na área de computação aplicada ? Só lendo esse post para saber como você pode mudar o mundo com eles !
Autor: Felipe Torres (www.fgtorres.com.br)
Link: http://www.fgtorres.com.br/2017/03/13/escolha-o-seu-projeto-open-source-na-area-de-saude/

**Comment by antoniolazaro** [comment]
Valeu @fgtorres !!
