### ISSUE TITLE
Programação Defensiva

### ISSUE THREAD

**Issue by thnery23** [javabahia/JVM-Links#29]
Tags: Boas Práticas de Programação
Link: http://nerideveloper.blogspot.com.br/2017/03/programacao-defensiva.html
Breve descrição: 
O que é programação Defensiva?
Esse tipo de programação é um particular de uma única linguagem?
Será que meu código ficará mais difícil de fazer ou até mesmo difícil de ler?

**Comment by malaquiasdev** [comment]
Thiago, vlw pela participação, seu texto foi publicado :)
