### ISSUE TITLE
Acompanhando as novidades do JUnit 5

### ISSUE THREAD

**Issue by luksrn** [javabahia/JVM-Links#56]
Titulo: Acompanhando as novidades do JUnit 5
Tags: JUnit
Link: https://medium.com/conversando-sobre-java/acompanhando-as-novidades-do-junit-5-e0c4e25bcaf5
Breve descrição: Neste texto são apresentadas as motivações e algumas novidades que virão na nova versão do JUnit 5.

**Comment by antoniolazaro** [comment]
divulgado hoje. Obrigado pela colaboração @luksrn
